server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/postbar?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

